=== zuhlke/customer-data-consent/consent_data_mods/consent_schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
      "consentGiver": { "type": "string" },
      "retentionPeriodDays": { "type": "number" },
      "dataCreationDate": { "type": "string", "format": "date" },
      "retentionDates": { "type": "string", "format": "date" },
      "consentedOrganisations": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1
      },
      "dataController": { "type": "string" },
      "foreignKeyProcess": { "type": "number" },
      "consentMethod": { "type": "string" },
      "lawfulBasis": { "type": "string" },
      "permittedProcessing": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1
      },
      "dataConsentStatus": { "type": "string" },
      "consentDate": { "type": "string", "format": "date" },
      "consentVersionRef": { "type": "string" },
      "typeProcessingPermitted": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1
      },
      "consentReviewDate": { "type": "string", "format": "date" },
      "dataZoneClassification": { "type": "string" },
      "datasetOwner": { "type": "string" },
      "processType": { "type": "string" },
      "processPurpose": { "type": "string" },
      "participatingOrganisations": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1
      },
      "dataProcessingConducted": {
        "type": "array",
        "items": { "type": "string" },
        "minItems": 1
      },
      "foreignKeyConsent": { "type": "number" },
      "precedentProcesses": { "type": "array", "items": {} },
      "dependentProcesses": { "type": "array", "items": {} },
      "outputDataList": { "type": "array", "items": {} }
    },
    "required": [
      "consentGiver",
      "retentionPeriodDays",
      "dataCreationDate",
      "retentionDates",
      "consentedOrganisations",
      "dataController",
      "foreignKeyProcess",
      "consentMethod",
      "lawfulBasis",
      "permittedProcessing",
      "dataConsentStatus",
      "consentDate",
      "consentVersionRef",
      "typeProcessingPermitted",
      "consentReviewDate",
      "dataZoneClassification",
      "datasetOwner",
      "processType",
      "processPurpose",
      "participatingOrganisations",
      "dataProcessingConducted",
      "foreignKeyConsent"
    ]
  }

=== zuhlke/customer-data-consent/test_files/correct.json
{
    "consentGiver": "Steer, Steven",
    "retentionPeriodDays": 90,
    "dataCreationDate":"23-03-2020",
    "retentionDates": "23-03-2024",
    "consentedOrganisations": ["UKPN", "NGESO","Octopus"],
    "dataController": "Steer, Steven",
    "foreignKeyProcess": 4328934,
    "consentMethod": "Online",
    "lawfulBasis": "Consent",
    "permittedProcessing": ["Marketing","Performance"],
    "dataConsentStatus": "Withdrawn",
    "consentDate": "23-03-2023",
    "consentVersionRef": "2",
    "typeProcessingPermitted": ["Analytics","Reporting","Marketing"],
    "consentReviewDate":"23-03-2023",
    "dataZoneClassification": "Unclassified",
    "datasetOwner": "Steer, Steven",
    "processType": "Analytics",
    "processPurpose": "Analytics",
    "participatingOrganisations": ["Octopus","EON","EDF"],
    "dataProcessingConducted": ["type1","type2"],
    "foreignKeyConsent":1234324,
    "precedentProcesses": [],
    "dependentProcesses": [],
    "outputDataList": []


}
